### PR TITLE
refactor: typehints and imports compatible to Python3.7

### PR DESCRIPTION
**Pull request by khubaibalam2000**
*Issue #, if available:*
This Pull Request resolve the issue mentioned in #627.

*Description of changes:*
Removed the imports as it is already supported in Python v3.7.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ShubhamChaturvedi7** [comment]
@khubaibalam2000 Could you use the semantically correct commit name / PR title?

**Comment by ShubhamChaturvedi7** [comment]
Also, a quick search shows that typehints and imports are scattered all over the place and we should fix them all: https://github.com/search?q=repo%3Aaws%2Faws-dynamodb-encryption-python+%22from+typing+import+Dict%22&type=code

**Comment by khubaibalam2000** [comment]
Sure, in the next commit, I am fixing these imports.

**Comment by texastony** [comment]
@khubaibalam2000 You recent commits, 
probably b4e40e3,
have broken the library.

You should be able to view the logs of the GitHub actions to examine
what tests failed.

You can look at the [GitHub Workflow File](https://github.com/aws/aws-dynamodb-encryption-python/blob/master/.github/workflows/ci_tests.yaml) 
in the repo for guidance on running the CI locally.

**Comment by khubaibalam2000** [comment]
@texastony Thank you for your guidance. Now, I am debugging and viewing the CI logs locally and fixing them. Will provide you with unbreakable commit soon :)

**Comment by ShubhamChaturvedi7** [comment]
@khubaibalam2000 There are still a lot of CIs failing. Please run them locally so that you can quickly iterate over the issues and fix them. Let us know if you need any help.

**Comment by khubaibalam2000** [comment]
Yes, as per your suggestion, I setup the CI locally and debug the code and found some errors, but now all the error are fixed. In my latest commit https://github.com/khubaibalam2000/aws-dynamodb-encryption-python/commit/ca5c9c4afb49cc100d6c6d5c8fef7affe3093982, all CIs are passing. Thank you for yours guidance.

**Comment by khubaibalam2000** [comment]
Yes, as per your suggestion, I setup the CI locally and debug the code and found some errors, but now all the error are fixed. In my latest commit https://github.com/aws/aws-dynamodb-encryption-python/pull/740/commits/7ac6b60b8cb7a22a2d5c2a1dba6a828a28596ae4, all CIs are passing. Thank you for yours guidance.

**Comment by khubaibalam2000** [comment]
All the checks are now passing. Is there any work left to do about the issue? or is it done.

**Review by lucasmcdonald3 — APPROVED** [review]
Thank you for your contribution!

**Comment by khubaibalam2000** [comment]
> Thank you for your contribution!

Welcome. Good to work with this repo. Going to work in the future issues and PRs too.

**Pull request merged**
