### PR TITLE
chore: Remove support for python 2

### PR DESCRIPTION
**Pull request by farleyb-amazon**
*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by texastony — DISMISSED** [review]

**Review by texastony — APPROVED** [review]

**Comment by texastony** [comment]
Glad you caught that. Have you run a generic grep for py2?

**Comment by texastony** [comment]
```
enum34; python_version < '3.4'
```
https://github.com/farleyb-amazon/aws-dynamodb-encryption-python/blob/2eaecca7d9146b58440664f390b9ed0bdb7e2a8c/requirements.txt#L4

**Review by texastony — COMMENTED** [review]
```
enum34; python_version < '3.4'
```
https://github.com/farleyb-amazon/aws-dynamodb-encryption-python/blob/2eaecca7d9146b58440664f390b9ed0bdb7e2a8c/requirements.txt#L4

I am not sure what the `;` notation does in a requirements file, but if I had to guess it would be for python < 3.4 require enum34. Which is no longer needed.

**Comment by farleyb-amazon** [comment]
> ```
> enum34; python_version < '3.4'
> ```
> 
> https://github.com/farleyb-amazon/aws-dynamodb-encryption-python/blob/2eaecca7d9146b58440664f390b9ed0bdb7e2a8c/requirements.txt#L4
> 
> I am not sure what the `;` notation does in a requirements file, but if I had to guess it would be for python < 3.4 require enum34. Which is no longer needed.

Yup, that's right. "If our python version is less than 3.4, we depend on enum34". Looks like the enum34 package is a backporting of a new feature introduced in Python 3.4 into older versions of Python, which means we do not need it. Good find!

**Review by texastony — APPROVED** [review]
Extra Groovy

**Pull request merged**
